title: Ester Tsai # your name (or website title) here
logo: "/images/circle.jpeg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Data Science student at UC San Diego
  <br><br>
  Experienced with Web Scraping and Data Visualization
  <br><br>
  <a href="https://www.linkedin.com/in/ester-tsai/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
